"""
🫚 GINGER UNIVERSE - Document Generator
Creates professional Word documents
"""

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os

def create_word_document(doctor_data, claude_response):
    """
    Creates a professional Word document from doctor profile
    """
    doc = Document()
    
    # Title
    title = doc.add_heading(doctor_data.get('name', 'Doctor Profile'), 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Qualifications
    if doctor_data.get('qualifications'):
        subtitle = doc.add_paragraph(' '.join(doctor_data.get('qualifications')))
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    doc.add_paragraph('_' * 80)
    
    # Add Claude content
    sections = claude_response.split('**')
    for i, section in enumerate(sections):
        section = section.strip()
        if not section:
            continue
        if i % 2 == 1:
            doc.add_heading(section, level=2)
        else:
            paragraphs = section.split('\n\n')
            for para_text in paragraphs:
                if para_text.strip():
                    doc.add_paragraph(para_text.strip())
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.add_run(f"\nGenerated by Ginger Universe | {datetime.now().strftime('%B %d, %Y')}\nginger.healthcare")
    
    # Save
    os.makedirs('/home/claude/ginger_universe/generated_docs', exist_ok=True)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filepath = f"/home/claude/ginger_universe/generated_docs/doctor_profile_{timestamp}.docx"
    doc.save(filepath)
    
    return filepath
