"""
🫚 Ginger Universe v3 — Document Generator
Creates professional Word documents from doctor profiles
"""

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os, tempfile


def create_word_document(doctor_name, profile_content):
    doc = Document()

    style = doc.styles['Normal']
    style.font.name = 'Calibri'
    style.font.size = Pt(11)

    # Title
    title = doc.add_heading(doctor_name or 'Doctor Profile', level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x0B, 0x25, 0x45)

    # Divider
    div = doc.add_paragraph()
    div.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = div.add_run('━' * 50)
    r.font.color.rgb = RGBColor(0xF2, 0x65, 0x22)
    r.font.size = Pt(8)

    # Content
    sections = profile_content.split('**')
    for i, section in enumerate(sections):
        section = section.strip()
        if not section:
            continue
        if i % 2 == 1:
            heading = doc.add_heading(section.strip(':').strip(), level=2)
            for run in heading.runs:
                run.font.color.rgb = RGBColor(0x0B, 0x25, 0x45)
        else:
            for line in section.split('\n'):
                line = line.strip()
                if not line:
                    continue
                if line.startswith(('- ', '• ', '* ')):
                    doc.add_paragraph(line[2:].strip(), style='List Bullet')
                elif line.startswith('## '):
                    heading = doc.add_heading(line[3:].strip(), level=2)
                    for run in heading.runs:
                        run.font.color.rgb = RGBColor(0x0B, 0x25, 0x45)
                else:
                    doc.add_paragraph(line)

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = footer.add_run(f"Generated by Ginger Healthcare | {datetime.now().strftime('%B %d, %Y')}")
    r.font.size = Pt(9)
    r.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)
    footer.add_run('\n')
    r2 = footer.add_run('ginger.healthcare')
    r2.font.size = Pt(9)
    r2.font.color.rgb = RGBColor(0xF2, 0x65, 0x22)

    # Save
    safe_name = "".join(c for c in (doctor_name or 'doctor') if c.isalnum() or c in ' -_').strip().replace(' ', '_')
    filename = f"{safe_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(tempfile.gettempdir(), filename)
    doc.save(filepath)
    return filepath
