"""
🫚 Ginger Universe — Document Generator
Creates professional Word documents from doctor profiles
"""

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os
import tempfile


def create_word_document(doctor_data, claude_response):
    """
    Creates a professional Word document from doctor profile.
    Returns the file path to the generated .docx
    """
    doc = Document()

    # ── Styles ────────────────────────────────────────────
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # ── Title ─────────────────────────────────────────────
    doctor_name = (doctor_data or {}).get('name', 'Doctor Profile')
    title = doc.add_heading(doctor_name, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    # Style the title run
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x0B, 0x25, 0x45)  # Ginger navy

    # ── Qualifications subtitle ───────────────────────────
    quals = (doctor_data or {}).get('qualifications', [])
    if quals:
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(', '.join(quals))
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    # ── Divider ───────────────────────────────────────────
    divider = doc.add_paragraph()
    divider.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = divider.add_run('━' * 50)
    run.font.color.rgb = RGBColor(0xF2, 0x65, 0x22)  # Ginger orange
    run.font.size = Pt(8)

    # ── Profile Content ───────────────────────────────────
    # Parse Claude's response (split on ** for bold headings)
    sections = claude_response.split('**')
    for i, section in enumerate(sections):
        section = section.strip()
        if not section:
            continue

        if i % 2 == 1:
            # This is a heading (was between ** markers)
            heading = doc.add_heading(section.strip(':').strip(), level=2)
            for run in heading.runs:
                run.font.color.rgb = RGBColor(0x0B, 0x25, 0x45)
        else:
            # This is body content
            lines = section.split('\n')
            for line in lines:
                line = line.strip()
                if not line:
                    continue

                if line.startswith('- ') or line.startswith('• '):
                    # Bullet point
                    doc.add_paragraph(line[2:].strip(), style='List Bullet')
                elif line.startswith('* '):
                    doc.add_paragraph(line[2:].strip(), style='List Bullet')
                else:
                    doc.add_paragraph(line)

    # ── Footer ────────────────────────────────────────────
    doc.add_paragraph()  # spacer
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run(f"Generated by Ginger Healthcare | {datetime.now().strftime('%B %d, %Y')}")
    run.font.size = Pt(9)
    run.font.color.rgb = RGBColor(0x9C, 0xA3, 0xAF)
    footer.add_run('\n')
    link_run = footer.add_run('ginger.healthcare')
    link_run.font.size = Pt(9)
    link_run.font.color.rgb = RGBColor(0xF2, 0x65, 0x22)

    # ── Save to temp directory ────────────────────────────
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    doctor_safe = "".join(c for c in (doctor_data or {}).get('name', 'doctor')
                         if c.isalnum() or c in ' -_').strip().replace(' ', '_')
    filename = f"{doctor_safe}_{timestamp}.docx"
    filepath = os.path.join(tempfile.gettempdir(), filename)
    doc.save(filepath)

    return filepath
